import { Toaster } from "react-hot-toast";
import "./globals.css";
import UserProvider from "@/context/UserContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster
          position="top-center"
          reverseOrder={false}
          toastOptions={{
            success: {
              style: {
                background: "#0e1113",
                color: "#e0e0e0",
              },
            },
            error: {
              style: {
                background: "#0e1113",
                color: "#e0e0e0",
              },
            },
          }}
        />
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
